# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
blank_lines: true
bullet: true
html: true
indentation: true
line_length: true
MD013:
  line_length: 150
spaces: true
url: true
whitespace: true
